CREATE TABLE `race_accommodations` (
	`id` text PRIMARY KEY NOT NULL,
	`race_id` text NOT NULL,
	`name` text NOT NULL,
	`address` text DEFAULT '' NOT NULL,
	`check_in_date` text NOT NULL,
	`check_out_date` text NOT NULL,
	`reservation_code` text DEFAULT '' NOT NULL,
	`room_count` integer DEFAULT 0 NOT NULL,
	`guest_count` integer DEFAULT 0 NOT NULL,
	`currency` text DEFAULT 'EUR' NOT NULL,
	`total_cents` integer DEFAULT 0 NOT NULL,
	`payment_status` text DEFAULT 'unpaid' NOT NULL,
	`status` text DEFAULT 'planned' NOT NULL,
	`notes` text DEFAULT '' NOT NULL,
	`archived_at` integer,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `race_car_rentals` (
	`id` text PRIMARY KEY NOT NULL,
	`race_id` text NOT NULL,
	`company` text NOT NULL,
	`vehicle_type` text DEFAULT '' NOT NULL,
	`pickup_place` text NOT NULL,
	`return_place` text NOT NULL,
	`pickup_at` text NOT NULL,
	`return_at` text NOT NULL,
	`reservation_code` text DEFAULT '' NOT NULL,
	`license_plate` text DEFAULT '' NOT NULL,
	`driver_name` text DEFAULT '' NOT NULL,
	`currency` text DEFAULT 'EUR' NOT NULL,
	`total_cents` integer DEFAULT 0 NOT NULL,
	`status` text DEFAULT 'planned' NOT NULL,
	`notes` text DEFAULT '' NOT NULL,
	`archived_at` integer,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `race_flights` (
	`id` text PRIMARY KEY NOT NULL,
	`race_id` text NOT NULL,
	`direction` text DEFAULT 'outbound' NOT NULL,
	`departure_airport` text NOT NULL,
	`arrival_airport` text NOT NULL,
	`departure_at` text NOT NULL,
	`arrival_at` text NOT NULL,
	`airline` text DEFAULT '' NOT NULL,
	`flight_number` text DEFAULT '' NOT NULL,
	`reservation_code` text DEFAULT '' NOT NULL,
	`passengers_note` text DEFAULT '' NOT NULL,
	`baggage` text DEFAULT '' NOT NULL,
	`currency` text DEFAULT 'EUR' NOT NULL,
	`total_cents` integer DEFAULT 0 NOT NULL,
	`status` text DEFAULT 'planned' NOT NULL,
	`notes` text DEFAULT '' NOT NULL,
	`archived_at` integer,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
