"use client";

import { useEffect, useMemo, useState } from "react";
import { countryFlag } from "./countries";
import { RaceLogoBadge } from "./race-logo-badge";
import { RentalHistory } from "./rental-history";
import type { CarburetorRecord, MechanicRecord } from "./catalog-pages";

type Locale = "cs" | "en";
type Role = "superadmin" | "boss" | "mechanic";
type Assignment = { id: string; driverId: string; driverName: string; teamName: string; category: string; raceId: string; raceName: string; logoUrl: string; track: string; countryCode: string; startDate: string; endDate: string; raceStatus: "planned" | "active" | "completed"; engineId: string | null; engineCode: string; position: number };
type Service = { id: string; serviceDate: string; serviceType: "check" | "routine" | "full" | "repair"; mechanicId: string | null; mechanicName: string; workDone: string; replacedParts: string; notes: string; createdAt: number };
type DetailData = { carburetor: CarburetorRecord; assignments: Assignment[]; services: Service[]; mechanics: Pick<MechanicRecord, "id" | "name">[] };

export function CarburetorDetail({ carburetorId, locale, role, onBack, onEdit }: { carburetorId: string; locale: Locale; role: Role; onBack: () => void; onEdit: (carburetor: CarburetorRecord) => void }) {
  const [data, setData] = useState<DetailData | null>(null);
  const [tab, setTab] = useState<"overview" | "history" | "service">("overview");
  const [serviceOpen, setServiceOpen] = useState(false);
  async function load() {
    const response = await fetch(`/api/carburetor-records?id=${encodeURIComponent(carburetorId)}`, { cache: "no-store" });
    if (response.ok) setData(await response.json() as DetailData);
  }
  useEffect(() => { void load(); }, [carburetorId]);
  const current = useMemo(() => {
    const active = data?.assignments.find((item) => item.raceStatus === "active");
    return active ?? data?.assignments.filter((item) => item.raceStatus === "planned").sort((a, b) => a.startDate.localeCompare(b.startDate))[0] ?? null;
  }, [data]);

  if (!data) return <section className="panel empty-state"><span className="spinner" /><p>{locale === "cs" ? "Načítám kartu karburátoru…" : "Loading carburetor card…"}</p></section>;
  const carb = data.carburetor;
  return <div className="carb-detail">
    <button className="detail-back" type="button" onClick={onBack}>← {locale === "cs" ? "Zpět na karburátory" : "Back to carburetors"}</button>
    {(tab === "overview" || tab === "history") && <RentalHistory locale={locale} itemType="carburetor" resourceId={carb.id} title={tab === "overview" ? (locale === "cs" ? "Aktuální pronájem karburátoru" : "Current carburetor rental") : undefined} />}
    <section className={`panel carb-detail-hero tone-${(carb.family || "").toLowerCase()}`}><div className="carb-detail-mark">◉</div><div><span className="eyebrow">MM CARBURETOR CARD</span><div className="carb-title-line"><h2>{carb.code}</h2><Status value={carb.status} locale={locale} /></div><p>{carb.brand} · {carb.model} · {carb.category || carb.family}</p></div><div className="carb-hero-actions">{role !== "mechanic" && <button className="secondary-compact" type="button" onClick={() => onEdit(carb)}>✎ {locale === "cs" ? "Upravit" : "Edit"}</button>}<button className="primary-button" type="button" onClick={() => setServiceOpen(true)}>＋ {locale === "cs" ? "Přidat servis" : "Add service"}</button></div></section>
    <nav className="engine-tabs carb-tabs"><button className={tab === "overview" ? "active" : ""} type="button" onClick={() => setTab("overview")}>{locale === "cs" ? "Přehled" : "Overview"}</button><button className={tab === "history" ? "active" : ""} type="button" onClick={() => setTab("history")}>{locale === "cs" ? "Historie závodů" : "Race history"}<b>{data.assignments.length}</b></button><button className={tab === "service" ? "active" : ""} type="button" onClick={() => setTab("service")}>{locale === "cs" ? "Servisní historie" : "Service history"}<b>{data.services.length}</b></button></nav>
    {tab === "overview" && <div className="carb-overview-grid"><section className="panel carb-info-card"><span className="eyebrow">INFO</span><h3>{locale === "cs" ? "Informace o karburátoru" : "Carburetor information"}</h3><div className="detail-field-grid compact"><Field label={locale === "cs" ? "Kód" : "Code"} value={carb.code} /><Field label={locale === "cs" ? "Kategorie" : "Category"} value={carb.category || carb.family} /><Field label={locale === "cs" ? "Značka" : "Brand"} value={carb.brand} /><Field label="Model" value={carb.model} /><Field label={locale === "cs" ? "Stav" : "Status"} value={statusLabel(carb.status, locale)} /><Field label={locale === "cs" ? "Počet závodů" : "Race count"} value={String(data.assignments.length)} /></div></section><section className={`panel current-assignment ${current ? "assigned" : ""}`}><span className="eyebrow">{locale === "cs" ? "AKTUÁLNÍ PŘIŘAZENÍ" : "CURRENT ASSIGNMENT"}</span>{current ? <><div className="assignment-driver"><strong>{current.driverName}</strong><small>{current.teamName || "—"} · {current.category}</small></div><div className="race-history-identity current-race-logo"><RaceLogoBadge logoUrl={current.logoUrl} name={current.raceName} fallback={countryFlag(current.countryCode)} /><span><h3>{current.raceName}</h3><p>{countryFlag(current.countryCode)} {current.track} · {dateRange(current.startDate, current.endDate, locale)}</p></span></div><div className="paired-engine"><span>{locale === "cs" ? `Pozice karburátoru ${current.position}` : `Carburetor position ${current.position}`}</span><strong>{locale === "cs" ? "Motor" : "Engine"}: {current.engineCode || "—"}</strong></div></> : <div className="no-assignment"><strong>{locale === "cs" ? "Není přiřazen" : "Not assigned"}</strong><p>{locale === "cs" ? "Karburátor teď není nasazený na žádném plánovaném závodě." : "This carburetor is not assigned to an upcoming race."}</p></div>}</section><section className="panel carb-notes"><span className="eyebrow">{locale === "cs" ? "POZNÁMKY" : "NOTES"}</span><p>{carb.notes || (locale === "cs" ? "Bez poznámky" : "No notes")}</p></section><section className="panel carb-last-service"><span className="eyebrow">{locale === "cs" ? "POSLEDNÍ SERVIS" : "LAST SERVICE"}</span>{data.services[0] ? <><h3>{serviceLabel(data.services[0].serviceType, locale)}</h3><p>{dateOnly(data.services[0].serviceDate, locale)} · {data.services[0].mechanicName}</p><small>{data.services[0].workDone || data.services[0].notes || "—"}</small></> : <div className="no-assignment"><strong>{locale === "cs" ? "Zatím bez záznamu" : "No service record"}</strong></div>}</section></div>}
    {tab === "history" && <section className="panel carb-record-panel"><header><div><span className="eyebrow">RACE HISTORY</span><h3>{locale === "cs" ? "Piloti, závody a použité motory" : "Drivers, races and paired engines"}</h3></div></header>{data.assignments.length ? <div className="table-wrap"><table className="engine-table race-logo-history-table"><thead><tr><th>{locale === "cs" ? "Závod" : "Race"}</th><th>{locale === "cs" ? "Pilot" : "Driver"}</th><th>{locale === "cs" ? "Kategorie" : "Category"}</th><th>{locale === "cs" ? "Motor" : "Engine"}</th><th>{locale === "cs" ? "Pozice" : "Position"}</th><th>{locale === "cs" ? "Stav závodu" : "Race status"}</th></tr></thead><tbody>{data.assignments.map((item) => <tr key={`${item.id}-${item.position}`}><td><div className="race-history-identity"><RaceLogoBadge logoUrl={item.logoUrl} name={item.raceName} fallback={countryFlag(item.countryCode)} size="small" /><span><strong>{item.raceName}</strong><small>{item.track} · {dateRange(item.startDate, item.endDate, locale)}</small></span></div></td><td><strong>{item.driverName}</strong><small>{item.teamName || "—"}</small></td><td>{item.category}</td><td><span className="equipment-code">{item.engineCode || "—"}</span></td><td>{item.position}</td><td><span className={`status-pill ${item.raceStatus === "completed" ? "neutral" : "info-pill"}`}>{raceStatus(item.raceStatus, locale)}</span></td></tr>)}</tbody></table></div> : <Empty text={locale === "cs" ? "Karburátor zatím nebyl přiřazen k závodu." : "No race assignments yet."} />}</section>}
    {tab === "service" && <section className="panel carb-record-panel"><header><div><span className="eyebrow">SERVICE CARD</span><h3>{locale === "cs" ? "Servisní historie" : "Service history"}</h3></div><button className="primary-button" type="button" onClick={() => setServiceOpen(true)}>＋ {locale === "cs" ? "Přidat servis" : "Add service"}</button></header>{data.services.length ? <div className="table-wrap"><table className="engine-table"><thead><tr><th>{locale === "cs" ? "Datum" : "Date"}</th><th>{locale === "cs" ? "Typ servisu" : "Service type"}</th><th>{locale === "cs" ? "Mechanik" : "Mechanic"}</th><th>{locale === "cs" ? "Provedené práce" : "Work done"}</th><th>{locale === "cs" ? "Vyměněné díly" : "Replaced parts"}</th><th>{locale === "cs" ? "Poznámka" : "Notes"}</th></tr></thead><tbody>{data.services.map((item) => <tr key={item.id}><td>{dateOnly(item.serviceDate, locale)}</td><td><strong>{serviceLabel(item.serviceType, locale)}</strong></td><td>{item.mechanicName}</td><td>{item.workDone || "—"}</td><td>{item.replacedParts || "—"}</td><td>{item.notes || "—"}</td></tr>)}</tbody></table></div> : <Empty text={locale === "cs" ? "Zatím bez servisních záznamů." : "No service records yet."} />}</section>}
    {serviceOpen && <ServiceForm carburetorId={carb.id} mechanics={data.mechanics} locale={locale} onClose={() => setServiceOpen(false)} onSaved={async () => { setServiceOpen(false); await load(); setTab("service"); }} />}
  </div>;
}

function ServiceForm({ carburetorId, mechanics, locale, onClose, onSaved }: { carburetorId: string; mechanics: Array<{ id: string; name: string }>; locale: Locale; onClose: () => void; onSaved: () => void }) {
  const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const payload = Object.fromEntries(new FormData(event.currentTarget).entries()); const response = await fetch("/api/carburetor-records", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...payload, carburetorId }) }); const result = await response.json() as { error?: string }; if (!response.ok) { setError(result.error || "Save failed"); setSaving(false); return; } onSaved(); }
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="modal" role="dialog" aria-modal="true"><div className="modal-header"><div><span className="eyebrow">SERVICE CARD</span><h2>{locale === "cs" ? "Nový servis karburátoru" : "New carburetor service"}</h2></div><button className="close-button" type="button" onClick={onClose}>×</button></div><form onSubmit={submit}><div className="form-grid"><label><span>{locale === "cs" ? "Datum" : "Date"} *</span><input type="date" name="serviceDate" required autoFocus defaultValue={todayIso()} /></label><label><span>{locale === "cs" ? "Typ servisu" : "Service type"} *</span><select name="serviceType" defaultValue="routine"><option value="check">{locale === "cs" ? "Kontrola" : "Check"}</option><option value="routine">{locale === "cs" ? "Běžný servis" : "Routine service"}</option><option value="full">{locale === "cs" ? "Kompletní servis" : "Full service"}</option><option value="repair">{locale === "cs" ? "Oprava" : "Repair"}</option></select></label><label className="full-field"><span>{locale === "cs" ? "Mechanik" : "Mechanic"}</span><select name="mechanicId" defaultValue=""><option value="">{locale === "cs" ? "Přihlášený uživatel" : "Signed-in user"}</option>{mechanics.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="full-field"><span>{locale === "cs" ? "Provedené práce" : "Work done"}</span><textarea name="workDone" rows={3} placeholder={locale === "cs" ? "Vyčištění, kontrola membrán, nastavení…" : "Cleaning, diaphragm inspection, setup…"} /></label><label className="full-field"><span>{locale === "cs" ? "Vyměněné díly" : "Replaced parts"}</span><textarea name="replacedParts" rows={2} /></label><label className="full-field"><span>{locale === "cs" ? "Poznámka" : "Notes"}</span><textarea name="notes" rows={2} /></label></div>{error && <p className="form-error">{error}</p>}<div className="modal-actions"><span className="modal-actions-spacer" /><button className="secondary-compact" type="button" onClick={onClose}>{locale === "cs" ? "Zrušit" : "Cancel"}</button><button className="primary-button" type="submit" disabled={saving}>{saving ? (locale === "cs" ? "Ukládám…" : "Saving…") : (locale === "cs" ? "Uložit servis" : "Save service")}</button></div></form></section></div>;
}

function Field({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><strong>{value || "—"}</strong></div>; }
function Empty({ text }: { text: string }) { return <div className="empty-state"><span className="empty-engine">◉</span><p>{text}</p></div>; }
function Status({ value, locale }: { value: string; locale: Locale }) { return <span className={`status-pill ${value === "ready" ? "success" : value === "storage" ? "neutral" : "warning-pill"}`}>{statusLabel(value, locale)}</span>; }
function statusLabel(value: string, locale: Locale) { const labels: Record<string, [string, string]> = { ready: ["Připraveno", "Ready"], service: ["Servis", "Service"], storage: ["Sklad", "Storage"], retired: ["Vyřazen", "Retired"] }; return (labels[value] ?? [value, value])[locale === "cs" ? 0 : 1]; }
function raceStatus(value: Assignment["raceStatus"], locale: Locale) { const labels = { planned: ["Plánováno", "Planned"], active: ["Probíhá", "Active"], completed: ["Dokončeno", "Completed"] } as const; return labels[value][locale === "cs" ? 0 : 1]; }
function serviceLabel(value: Service["serviceType"], locale: Locale) { const labels = { check: ["Kontrola", "Check"], routine: ["Běžný servis", "Routine service"], full: ["Kompletní servis", "Full service"], repair: ["Oprava", "Repair"] } as const; return labels[value][locale === "cs" ? 0 : 1]; }
function dateOnly(value: string, locale: Locale) { const [year, month, day] = value.split("-").map(Number); return new Intl.DateTimeFormat(locale === "cs" ? "cs-CZ" : "en-GB", { day: "numeric", month: "short", year: "numeric" }).format(new Date(year, month - 1, day)); }
function dateRange(start: string, end: string, locale: Locale) { return `${dateOnly(start, locale)} – ${dateOnly(end, locale)}`; }
function todayIso() { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
