"use client";

import { useEffect, useState } from "react";
import type { RentalRecord } from "./rental-page";

type Locale = "cs" | "en";
type Props = { locale: Locale; itemType?: "engine" | "carburetor"; resourceId?: string; customerId?: string; teamId?: string; title?: string };

export function RentalHistory({ locale, itemType, resourceId, customerId, teamId, title }: Props) {
  const [rentals, setRentals] = useState<RentalRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  useEffect(() => {
    let active = true; const params = new URLSearchParams();
    if (itemType && resourceId) { params.set("itemType", itemType); params.set("resourceId", resourceId); }
    if (customerId) params.set("customerId", customerId); if (teamId) params.set("teamId", teamId);
    fetch(`/api/equipment-rentals?${params}`, { cache: "no-store" }).then(async (response) => { const data = await response.json() as { rentals?: RentalRecord[] }; if (!response.ok || !data.rentals) throw new Error(); return data.rentals; }).then((records) => { if (active) { setRentals(records); setError(false); } }).catch(() => { if (active) setError(true); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [itemType, resourceId, customerId, teamId]);
  const current = rentals.find((rental) => !["returned", "cancelled"].includes(rental.status)) ?? null;
  return <section className="panel rental-history-card"><header><div><span className="eyebrow">RENTAL HISTORY</span><h3>{title ?? (locale === "cs" ? "Historie pronájmů" : "Rental history")}</h3></div><b>{rentals.length}</b></header>{loading && <div className="empty-state"><span className="spinner" /><p>{locale === "cs" ? "Načítám historii…" : "Loading history…"}</p></div>}{!loading && error && <div className="empty-inline"><strong>{locale === "cs" ? "Historii se nepodařilo načíst." : "Could not load rental history."}</strong></div>}{!loading && !error && current && <div className={`rental-current-card ${current.isOverdue ? "overdue" : ""}`}><div><span>{locale === "cs" ? "Aktuálně půjčeno" : "Currently rented"}</span><strong>{current.customerName}</strong></div><div><span>{locale === "cs" ? "Od kdy" : "Since"}</span><strong>{date(current.handoverDate, locale)}</strong></div><div><span>{locale === "cs" ? "Plánované vrácení" : "Planned return"}</span><strong>{date(current.plannedReturnDate, locale)}</strong></div><div><span>{locale === "cs" ? "Stav" : "Status"}</span><strong>{statusLabel(current.status, locale)}</strong></div></div>}{!loading && !error && rentals.length > 0 && <div className="table-wrap"><table className="engine-table rental-history-table"><thead><tr><th>{locale === "cs" ? "Pronájem" : "Rental"}</th><th>{locale === "cs" ? "Komu / pilot" : "Rented to / driver"}</th><th>{locale === "cs" ? "Termín" : "Dates"}</th><th>{locale === "cs" ? "Účtované dny" : "Billable days"}</th><th>{locale === "cs" ? "Cena" : "Price"}</th><th>{locale === "cs" ? "Stav" : "Status"}</th></tr></thead><tbody>{rentals.map((rental) => { const item = itemType && resourceId ? rental.items.find((entry) => entry.itemType === itemType && entry.resourceId === resourceId) : null; const days = item?.billableDays ?? (item?.returnedDate ? dayCount(rental.handoverDate, item.returnedDate) : rental.actualDays ?? rental.plannedDays); const price = item ? item.dailyPriceCents * item.quantity * days : rental.totalCents; return <tr key={rental.id}><td><strong>{rental.rentalNumber}</strong><small>{date(rental.createdDate, locale)}</small></td><td><strong>{rental.customerName}</strong>{item?.driverName && <small>{item.driverName}</small>}</td><td><strong>{date(rental.handoverDate, locale)}</strong><small>{date(item?.returnedDate || rental.actualReturnDate || rental.plannedReturnDate, locale)}</small></td><td>{days}</td><td>{money(price, rental.currency, locale)}</td><td>{statusLabel(rental.status, locale)}</td></tr>; })}</tbody></table></div>}{!loading && !error && rentals.length === 0 && <div className="empty-inline"><strong>{locale === "cs" ? "Zatím bez pronájmu" : "No rentals yet"}</strong><p>{locale === "cs" ? "Historie se vytvoří automaticky po uložení pronájmu." : "History is created automatically when a rental is saved."}</p></div>}</section>;
}

function dayCount(start: string, end: string) { return Math.max(1, Math.floor((Date.parse(`${end}T00:00:00Z`) - Date.parse(`${start}T00:00:00Z`)) / 86_400_000) + 1); }
function date(value: string, locale: Locale) { return new Intl.DateTimeFormat(locale === "cs" ? "cs-CZ" : "en-GB").format(new Date(`${value}T00:00:00`)); }
function money(cents: number, currency: "CZK" | "EUR", locale: Locale) { return new Intl.NumberFormat(locale === "cs" ? "cs-CZ" : "en-GB", { style: "currency", currency }).format(cents / 100); }
function statusLabel(value: string, locale: Locale) { const labels: Record<string, [string, string]> = { preparing: ["Připravuje se", "Preparing"], sent: ["Odesláno", "Sent"], active: ["Aktivní", "Active"], overdue: ["Po termínu", "Overdue"], returned: ["Vráceno", "Returned"], cancelled: ["Stornováno", "Cancelled"] }; return (labels[value] ?? [value, value])[locale === "cs" ? 0 : 1]; }
