"use client";

import { useEffect, useMemo, useState } from "react";
import type { CatalogData } from "./catalog-pages";
import type { CustomerRecord, InventoryPartRecord, ServiceCatalogRecord } from "./commerce-pages";

type Locale = "cs" | "en";
type Role = "superadmin" | "boss" | "mechanic";
type ItemType = "engine" | "carburetor" | "part" | "service" | "other";
type PaymentMethod = "cash" | "card" | "bank_transfer" | "invoice" | "other";
type BuyerMode = "customer" | "new" | "team";
type SalesTab = "sales" | "engines" | "carburetors";

export type EngineChoice = { id: string; code: string; category: string; family: string; currentConfiguration?: string | null; kzGeneration?: string | null; soldAt?: number | null };
type SaleItem = { id?: string; itemType: ItemType; resourceId: string; category?: string; code: string; description: string; descriptionEn?: string; quantity: number; unitPriceCents: number; lineTotalCents?: number };
export type SaleRecord = { id: string; raceId: string | null; customerId?: string | null; teamId?: string | null; raceName?: string | null; raceTrack?: string | null; saleNumber: string; saleDate: string; customerName: string; documentNumber: string; currency: "CZK" | "EUR"; totalCents: number; paymentMethod: PaymentMethod; isPaid: boolean; isDelivered: boolean; notes: string; voidedAt: number | null; voidedBy: string | null; items: SaleItem[] };
type SoldEquipment = { id: string; code: string; category: string; family: string; currentConfiguration?: string | null; kzGeneration?: string | null; brand?: string; model?: string; totalMinutes?: number; saleId: string; saleNumber: string; saleDate: string; customerName: string; currency: "CZK" | "EUR"; unitPriceCents: number };

const emptyCatalog: CatalogData = { raceTypes: [], teams: [], drivers: [], mechanics: [], vehicles: [], carburetors: [] };

export function SalesPage({ locale, role }: { locale: Locale; role: Role }) {
  const [sales, setSales] = useState<SaleRecord[]>([]); const [engines, setEngines] = useState<EngineChoice[]>([]); const [catalog, setCatalog] = useState<CatalogData>(emptyCatalog);
  const [soldEngines, setSoldEngines] = useState<SoldEquipment[]>([]); const [soldCarburetors, setSoldCarburetors] = useState<SoldEquipment[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const [editing, setEditing] = useState<SaleRecord | "new" | null>(null); const [tab, setTab] = useState<SalesTab>("sales");
  const [history, setHistory] = useState<{ type: "engine" | "carburetor"; item: SoldEquipment } | null>(null); const canManage = role !== "mechanic";
  async function load() {
    setLoading(true);
    try {
      const [salesResponse, enginesResponse, catalogResponse] = await Promise.all([fetch("/api/sales", { cache: "no-store" }), fetch("/api/engines", { cache: "no-store" }), fetch("/api/catalog", { cache: "no-store" })]);
      if (!salesResponse.ok || !enginesResponse.ok || !catalogResponse.ok) throw new Error();
      const salesData = await salesResponse.json() as { sales: SaleRecord[]; soldEngines: SoldEquipment[]; soldCarburetors: SoldEquipment[] };
      setSales(salesData.sales); setSoldEngines(salesData.soldEngines); setSoldCarburetors(salesData.soldCarburetors);
      setEngines((await enginesResponse.json() as { engines: EngineChoice[] }).engines); setCatalog(await catalogResponse.json() as CatalogData); setError(false);
    } catch { setError(true); } finally { setLoading(false); }
  }
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  async function voidSale(sale: SaleRecord) {
    if (role !== "superadmin" || sale.voidedAt || !window.confirm(locale === "cs" ? `Opravdu stornovat ${sale.saleNumber}? Motory, karburátory a skladové díly se vrátí do aktivní evidence.` : `Void ${sale.saleNumber}? Equipment and stock parts will be restored.`)) return;
    const response = await fetch("/api/sales", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: sale.id }) });
    if (!response.ok) return window.alert(locale === "cs" ? "Prodej se nepodařilo stornovat." : "Could not void sale."); await load();
  }
  const activeSales = useMemo(() => sales.filter((sale) => !sale.voidedAt), [sales]);
  const totals = useMemo(() => (["CZK", "EUR"] as const).map((currency) => ({ currency, cents: activeSales.filter((sale) => sale.currency === currency).reduce((sum, sale) => sum + sale.totalCents, 0) })).filter((entry) => entry.cents > 0), [activeSales]);
  return <div className="sales-page">
    <section className="panel sales-header"><div><span className="eyebrow">MM SALES REGISTER</span><h2>{locale === "cs" ? "Prodej" : "Sales"}</h2><p>{locale === "cs" ? "Prodeje, prodané vybavení a zachovaná provozní historie na jednom místě." : "Sales, sold equipment and preserved usage history in one place."}</p></div><div className="sales-header-actions">{totals.map((total) => <span key={total.currency}><small>{locale === "cs" ? "Aktivní prodeje" : "Active sales"} · {total.currency}</small><strong>{formatMoney(total.cents, total.currency, locale)}</strong></span>)}{canManage && <button className="primary-button" type="button" onClick={() => setEditing("new")}>＋ {locale === "cs" ? "Nový prodej" : "New sale"}</button>}</div></section>
    <nav className="sales-tabs" aria-label={locale === "cs" ? "Sekce prodeje" : "Sales sections"}>{([{ id: "sales", cs: "Aktivní prodeje", en: "Active sales", count: activeSales.length }, { id: "engines", cs: "Prodané motory", en: "Sold engines", count: soldEngines.length }, { id: "carburetors", cs: "Prodané karburátory", en: "Sold carburetors", count: soldCarburetors.length }] as const).map((item) => <button key={item.id} className={tab === item.id ? "active" : ""} type="button" onClick={() => setTab(item.id)}><span>{locale === "cs" ? item.cs : item.en}</span><b>{item.count}</b></button>)}</nav>
    <section className="panel data-panel sales-list">
      {loading && <div className="empty-state"><span className="spinner" /><p>{locale === "cs" ? "Načítám prodeje…" : "Loading sales…"}</p></div>}
      {!loading && error && <div className="empty-state error-state"><b>!</b><p>{locale === "cs" ? "Prodeje se nepodařilo načíst." : "Could not load sales."}</p></div>}
      {!loading && !error && tab === "sales" && <SalesTable sales={activeSales} locale={locale} role={role} onEdit={setEditing} onVoid={(sale) => { void voidSale(sale); }} />}
      {!loading && !error && tab === "engines" && <SoldEquipmentTable type="engine" items={soldEngines} locale={locale} onHistory={(item) => setHistory({ type: "engine", item })} />}
      {!loading && !error && tab === "carburetors" && <SoldEquipmentTable type="carburetor" items={soldCarburetors} locale={locale} onHistory={(item) => setHistory({ type: "carburetor", item })} />}
    </section>
    {editing && <SaleForm locale={locale} sale={editing === "new" ? null : editing} engines={engines} catalog={catalog} onClose={() => setEditing(null)} onSaved={async () => { setEditing(null); await load(); }} />}
    {history && <EquipmentHistoryDialog {...history} locale={locale} onClose={() => setHistory(null)} />}
  </div>;
}

function SalesTable({ sales, locale, role, onEdit, onVoid }: { sales: SaleRecord[]; locale: Locale; role: Role; onEdit: (sale: SaleRecord) => void; onVoid: (sale: SaleRecord) => void }) {
  if (!sales.length) return <div className="empty-state"><span className="empty-engine">¤</span><h2>{locale === "cs" ? "Zatím není evidován žádný aktivní prodej." : "No active sales recorded yet."}</h2></div>;
  return <div className="table-wrap sales-table-wrap"><table className="engine-table sales-table"><thead><tr><th>{locale === "cs" ? "Prodej" : "Sale"}</th><th>{locale === "cs" ? "Datum" : "Date"}</th><th>{locale === "cs" ? "Zákazník / tým" : "Customer / team"}</th><th>{locale === "cs" ? "Položky" : "Items"}</th><th>{locale === "cs" ? "Celkem" : "Total"}</th><th>{locale === "cs" ? "Akce" : "Actions"}</th></tr></thead><tbody>{sales.map((sale) => <tr key={sale.id}><td className="sale-number-cell"><strong>{sale.saleNumber}</strong>{sale.documentNumber && <small>{locale === "cs" ? "Doklad" : "Document"}: {sale.documentNumber}</small>}{sale.raceName && <small className="sale-race-link">🏁 {sale.raceName}</small>}</td><td className="sale-date-cell">{formatDate(sale.saleDate, locale)}</td><td className="sale-buyer-cell"><strong>{sale.customerName}</strong><div className="sale-payment-meta"><span>{paymentMethodLabel(sale.paymentMethod, locale)}</span><b className={sale.isPaid ? "paid" : "unpaid"}>{sale.isPaid ? `✓ ${locale === "cs" ? "Zaplaceno" : "Paid"}` : `○ ${locale === "cs" ? "Nezaplaceno" : "Unpaid"}`}</b>{sale.isDelivered && <b className="delivered">✓ {locale === "cs" ? "Předáno" : "Delivered"}</b>}</div></td><td><div className="sale-items-summary">{sale.items.map((item, index) => <span key={item.id ?? index}>{item.quantity > 1 ? `${item.quantity}× ` : ""}{item.code || saleItemDescription(item, locale)}</span>)}</div></td><td className="sale-total-cell"><strong>{formatMoney(sale.totalCents, sale.currency, locale)}</strong></td><td>{role !== "mechanic" && <div className="record-actions sale-row-actions"><button type="button" onClick={() => onEdit(sale)}>{locale === "cs" ? "Upravit" : "Edit"}</button>{role === "superadmin" && <button className="delete" type="button" onClick={() => onVoid(sale)}>{locale === "cs" ? "Stornovat" : "Void"}</button>}</div>}</td></tr>)}</tbody></table></div>;
}

function SoldEquipmentTable({ type, items, locale, onHistory }: { type: "engine" | "carburetor"; items: SoldEquipment[]; locale: Locale; onHistory: (item: SoldEquipment) => void }) {
  if (!items.length) return <div className="empty-state"><span className="empty-engine">◫</span><h2>{locale === "cs" ? "Zatím bez prodaného vybavení" : "No sold equipment yet"}</h2></div>;
  return <div className="table-wrap"><table className="engine-table sold-equipment-table"><thead><tr><th>{locale === "cs" ? "Kód" : "Code"}</th><th>{locale === "cs" ? "Kategorie / typ" : "Category / type"}</th><th>{locale === "cs" ? "Prodej" : "Sale"}</th><th>{locale === "cs" ? "Komu" : "Buyer"}</th><th>{locale === "cs" ? "Cena" : "Price"}</th><th>{locale === "cs" ? "Kompletní historie" : "Full history"}</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.code}</strong>{type === "carburetor" && <small>{[item.brand, item.model].filter(Boolean).join(" · ")}</small>}</td><td><strong>{item.category || item.family}</strong><small>{item.currentConfiguration || item.kzGeneration || item.family}</small></td><td><strong>{item.saleNumber}</strong><small>{formatDate(item.saleDate, locale)}</small></td><td>{item.customerName}</td><td>{formatMoney(item.unitPriceCents, item.currency, locale)}</td><td><button className="secondary-compact" type="button" onClick={() => onHistory(item)}>{locale === "cs" ? "Zobrazit použití a servis" : "View usage and service"}</button></td></tr>)}</tbody></table></div>;
}

export function SaleForm({ locale, sale, engines, catalog, raceId, raceLabel, initialDate, onClose, onSaved }: { locale: Locale; sale: SaleRecord | null; engines: EngineChoice[]; catalog: CatalogData; raceId?: string; raceLabel?: string; initialDate?: string; onClose: () => void; onSaved: () => void }) {
  const [currency, setCurrency] = useState<"CZK" | "EUR">(sale?.currency ?? "CZK"); const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>(sale?.paymentMethod ?? "cash");
  const [isPaid, setIsPaid] = useState(Boolean(sale?.isPaid)); const [isDelivered, setIsDelivered] = useState(Boolean(sale?.isDelivered)); const [items, setItems] = useState<SaleItem[]>(sale?.items.map((item) => ({ ...item })) ?? [emptyItem()]);
  const [customers, setCustomers] = useState<CustomerRecord[]>([]); const [services, setServices] = useState<ServiceCatalogRecord[]>([]); const [parts, setParts] = useState<InventoryPartRecord[]>([]);
  const initialMode: BuyerMode = sale?.teamId ? "team" : sale?.customerId ? "customer" : "new"; const [buyerMode, setBuyerMode] = useState<BuyerMode>(initialMode);
  const [customerId, setCustomerId] = useState(sale?.customerId ?? ""); const [teamId, setTeamId] = useState(sale?.teamId ?? ""); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { let active = true; Promise.all([fetch("/api/customers", { cache: "no-store" }), fetch("/api/service-catalog", { cache: "no-store" }), fetch("/api/inventory", { cache: "no-store" })]).then(async ([a, b, c]) => { if (!a.ok || !b.ok || !c.ok) throw new Error(); const customerData = await a.json() as { customers: CustomerRecord[] }; const serviceData = await b.json() as { services: ServiceCatalogRecord[] }; const partData = await c.json() as { parts: InventoryPartRecord[] }; if (active) { setCustomers(customerData.customers); setServices(serviceData.services); setParts(partData.parts); } }).catch(() => { if (active) setError(locale === "cs" ? "Nepodařilo se načíst zákazníky, sklad nebo ceník." : "Could not load customers, stock or price list."); }); return () => { active = false; }; }, [locale]);
  const total = items.reduce((sum, item) => sum + item.quantity * item.unitPriceCents, 0);
  function updateItem(index: number, patch: Partial<SaleItem>) { setItems((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item)); }
  function changeCurrency(next: "CZK" | "EUR") { setCurrency(next); setItems((current) => current.map((item) => { if (item.itemType !== "service") return item; const service = services.find((entry) => entry.id === item.resourceId); return service ? { ...item, unitPriceCents: next === "CZK" ? service.priceCzkCents : service.priceEurCents } : item; })); }
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true); setError(""); const form = new FormData(event.currentTarget);
    const newCustomer = buyerMode === "new" ? { name: form.get("newCustomerName"), phone: form.get("newCustomerPhone"), email: form.get("newCustomerEmail"), address: form.get("newCustomerAddress"), companyId: form.get("newCustomerCompanyId"), vatId: form.get("newCustomerVatId") } : null;
    try { const response = await fetch("/api/sales", { method: sale ? "PUT" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: sale?.id, raceId: raceId ?? sale?.raceId ?? null, saleDate: form.get("saleDate"), customerId: buyerMode === "customer" ? customerId : null, teamId: buyerMode === "team" ? teamId : null, newCustomer, documentNumber: form.get("documentNumber"), currency, paymentMethod, isPaid, isDelivered, notes: form.get("notes"), items }) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error || "Save failed"); onSaved(); }
    catch (saveError) { setError(localizeSaleError(saveError instanceof Error ? saveError.message : "Save failed", locale)); setSaving(false); }
  }
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="modal sale-modal" role="dialog" aria-modal="true"><div className="modal-header"><div><span className="eyebrow">MM SALES REGISTER</span><h2>{sale ? (locale === "cs" ? `Upravit ${sale.saleNumber}` : `Edit ${sale.saleNumber}`) : (locale === "cs" ? "Nový prodej" : "New sale")}</h2></div><button className="close-button" type="button" onClick={onClose}>×</button></div><form onSubmit={submit}>
    {raceLabel && <div className="sale-race-context">🏁 <strong>{locale === "cs" ? "Prodej na závodě" : "Race sale"}:</strong> {raceLabel}</div>}
    <div className="sale-form-grid"><label><span>{locale === "cs" ? "Datum prodeje" : "Sale date"} *</span><input type="date" name="saleDate" defaultValue={sale?.saleDate ?? initialDate ?? today()} required autoFocus /></label><label><span>{locale === "cs" ? "Číslo faktury / dokladu" : "Invoice / document number"}</span><input name="documentNumber" defaultValue={sale?.documentNumber ?? ""} /></label><label><span>{locale === "cs" ? "Měna cen" : "Price currency"}</span><select value={currency} onChange={(event) => changeCurrency(event.target.value as "CZK" | "EUR")}><option value="CZK">CZK — Kč</option><option value="EUR">EUR — €</option></select></label><label><span>{locale === "cs" ? "Forma platby" : "Payment method"}</span><select value={paymentMethod} onChange={(event) => setPaymentMethod(event.target.value as PaymentMethod)}><option value="cash">{locale === "cs" ? "Hotově" : "Cash"}</option><option value="card">{locale === "cs" ? "Kartou" : "Card"}</option><option value="bank_transfer">{locale === "cs" ? "Převodem" : "Bank transfer"}</option><option value="invoice">{locale === "cs" ? "Faktura" : "Invoice"}</option><option value="other">{locale === "cs" ? "Jinak" : "Other"}</option></select></label><label className="sale-state-check"><input type="checkbox" checked={isPaid} onChange={(event) => setIsPaid(event.target.checked)} /><span>{locale === "cs" ? "Zaplaceno" : "Paid"}</span></label><label className="sale-state-check"><input type="checkbox" checked={isDelivered} onChange={(event) => setIsDelivered(event.target.checked)} /><span>{locale === "cs" ? "Předáno" : "Delivered"}</span></label></div>
    <BuyerFields locale={locale} mode={buyerMode} onMode={setBuyerMode} customerId={customerId} onCustomer={setCustomerId} teamId={teamId} onTeam={setTeamId} customers={customers} catalog={catalog} sale={sale} />
    <div className="sale-form-items"><div className="sale-form-heading"><div><span className="eyebrow">ITEMS</span><h3>{locale === "cs" ? "Prodané položky" : "Sold items"}</h3><p>{items.length} {locale === "cs" ? "položek" : "items"}</p></div><button className="secondary-compact" type="button" onClick={() => setItems((current) => [...current, emptyItem()])}>＋ {locale === "cs" ? "Přidat položku" : "Add item"}</button></div>{items.map((item, index) => <SaleItemRow key={index} index={index} item={item} currency={currency} engines={engines} catalog={catalog} services={services} parts={parts} currentSale={sale} locale={locale} onChange={(patch) => updateItem(index, patch)} onRemove={() => setItems((current) => current.filter((_, itemIndex) => itemIndex !== index))} />)}</div>
    <div className="sale-form-footer"><label><span>{locale === "cs" ? "Poznámka" : "Notes"}</span><textarea name="notes" rows={3} defaultValue={sale?.notes ?? ""} /></label><div><small>{locale === "cs" ? "Celkem" : "Total"}</small><strong>{formatMoney(total, currency, locale)}</strong></div></div>
    {error && <p className="form-error">{error}</p>}<div className="modal-actions sale-modal-actions"><span className="modal-actions-spacer" /><button className="secondary-compact" type="button" onClick={onClose} disabled={saving}>{locale === "cs" ? "Zrušit" : "Cancel"}</button><button className="primary-button" type="submit" disabled={saving || !items.length}>{saving ? (locale === "cs" ? "Ukládám…" : "Saving…") : (locale === "cs" ? "Uložit prodej" : "Save sale")}</button></div>
  </form></section></div>;
}

function BuyerFields({ locale, mode, onMode, customerId, onCustomer, teamId, onTeam, customers, catalog, sale }: { locale: Locale; mode: BuyerMode; onMode: (mode: BuyerMode) => void; customerId: string; onCustomer: (id: string) => void; teamId: string; onTeam: (id: string) => void; customers: CustomerRecord[]; catalog: CatalogData; sale: SaleRecord | null }) {
  return <fieldset className="sale-buyer"><legend>{locale === "cs" ? "Komu se prodává" : "Buyer"} *</legend><div className="sale-buyer-modes"><button type="button" className={mode === "customer" ? "active" : ""} onClick={() => onMode("customer")}>{locale === "cs" ? "Existující zákazník" : "Existing customer"}</button><button type="button" className={mode === "new" ? "active" : ""} onClick={() => onMode("new")}>{locale === "cs" ? "Nový zákazník" : "New customer"}</button><button type="button" className={mode === "team" ? "active" : ""} onClick={() => onMode("team")}>{locale === "cs" ? "Tým" : "Team"}</button></div>
    {mode === "customer" && <label><span>{locale === "cs" ? "Zákazník" : "Customer"}</span><select required value={customerId} onChange={(event) => onCustomer(event.target.value)}><option value="">{locale === "cs" ? "Vyber zákazníka…" : "Select customer…"}</option>{customers.map((item) => <option key={item.id} value={item.id}>{item.name}{item.email ? ` · ${item.email}` : ""}</option>)}</select></label>}
    {mode === "team" && <label><span>{locale === "cs" ? "Tým" : "Team"}</span><select required value={teamId} onChange={(event) => onTeam(event.target.value)}><option value="">{locale === "cs" ? "Vyber tým…" : "Select team…"}</option>{catalog.teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select></label>}
    {mode === "new" && <div className="sale-new-customer"><label><span>{locale === "cs" ? "Jméno / firma" : "Name / company"} *</span><input name="newCustomerName" required defaultValue={!sale?.customerId && !sale?.teamId ? sale?.customerName ?? "" : ""} /></label><label><span>{locale === "cs" ? "Telefon" : "Phone"}</span><input name="newCustomerPhone" /></label><label><span>E-mail</span><input name="newCustomerEmail" type="email" /></label><label><span>IČO</span><input name="newCustomerCompanyId" /></label><label><span>DIČ</span><input name="newCustomerVatId" /></label><label><span>{locale === "cs" ? "Adresa" : "Address"}</span><input name="newCustomerAddress" /></label></div>}
  </fieldset>;
}

function SaleItemRow({ index, item, currency, engines, catalog, services, parts, currentSale, locale, onChange, onRemove }: { index: number; item: SaleItem; currency: "CZK" | "EUR"; engines: EngineChoice[]; catalog: CatalogData; services: ServiceCatalogRecord[]; parts: InventoryPartRecord[]; currentSale: SaleRecord | null; locale: Locale; onChange: (patch: Partial<SaleItem>) => void; onRemove: () => void }) {
  const currentResourceIds = new Set(currentSale?.items.map((entry) => entry.resourceId).filter(Boolean) ?? []); const availableEngines = engines.filter((entry) => !entry.soldAt || currentResourceIds.has(entry.id)); const availableCarbs = catalog.carburetors.filter((entry) => !entry.soldAt || currentResourceIds.has(entry.id));
  const resources = item.itemType === "engine" ? availableEngines : availableCarbs; const selected = resources.find((entry) => entry.id === item.resourceId); const category = item.category || selected?.category || "";
  const categories = Array.from(new Set(resources.map((entry) => entry.category || entry.family).filter(Boolean))).sort(categorySort); const filteredResources = category ? resources.filter((entry) => (entry.category || entry.family) === category) : resources;
  const selectedService = item.itemType === "service" ? services.find((entry) => entry.id === item.resourceId) : undefined;
  const serviceDescription = locale === "en" ? (selectedService?.descriptionEn || selectedService?.descriptionCs || item.descriptionEn || item.description) : (selectedService?.descriptionCs || selectedService?.description || item.description);
  function changeType(type: ItemType) { onChange({ itemType: type, resourceId: "", category: "", code: "", description: "", descriptionEn: "", quantity: 1, unitPriceCents: 0 }); }
  return <div className={`sale-item-row ${item.itemType === "service" ? "has-service" : ""}`}><span className="sale-item-number">{index + 1}</span><label className="sale-item-type"><span>{locale === "cs" ? "Typ položky" : "Item type"}</span><select value={item.itemType} onChange={(event) => changeType(event.target.value as ItemType)}><option value="other">{locale === "cs" ? "Ostatní / díly" : "Other / parts"}</option><option value="part">{locale === "cs" ? "Díl ze skladu" : "Stock part"}</option><option value="service">{locale === "cs" ? "Servis / práce" : "Service / work"}</option><option value="engine">Motor</option><option value="carburetor">Karburátor</option></select></label>
    {(item.itemType === "engine" || item.itemType === "carburetor") && <><label className="sale-item-category"><span>{locale === "cs" ? "Kategorie" : "Category"}</span><select value={category} required onChange={(event) => onChange({ category: event.target.value, resourceId: "", code: "", description: "" })}><option value="">—</option>{categories.map((value) => <option key={value}>{value}</option>)}</select></label><label className="sale-item-resource"><span>{item.itemType === "engine" ? "Motor" : "Karburátor"} *</span><select required value={item.resourceId} disabled={!category} onChange={(event) => { const resource = filteredResources.find((entry) => entry.id === event.target.value); onChange({ resourceId: event.target.value, code: resource?.code ?? "", description: resource ? `${item.itemType === "engine" ? "Motor" : "Karburátor"} ${resource.code}` : "" }); }}><option value="">—</option>{filteredResources.map((resource) => <option key={resource.id} value={resource.id}>{resource.code} · {resource.family}</option>)}</select></label></>}
    {item.itemType === "part" && <label className="sale-item-resource sale-item-wide"><span>{locale === "cs" ? "Díl ze skladu" : "Stock part"} *</span><select required={!currentSale || !item.description || Boolean(item.resourceId)} value={item.resourceId} onChange={(event) => { const part = parts.find((entry) => entry.id === event.target.value); onChange({ resourceId: event.target.value, code: part?.code ?? item.code, description: part?.name ?? item.description, unitPriceCents: part ? (currency === "CZK" ? part.priceCzkCents : part.priceEurCents) : item.unitPriceCents }); }}><option value="">{currentSale && item.description && !item.resourceId ? `${locale === "cs" ? "Historická položka" : "Historical item"}: ${item.description}` : (locale === "cs" ? "Vyber díl…" : "Select part…")}</option>{parts.map((part) => <option key={part.id} value={part.id} disabled={part.quantity === 0 && part.id !== item.resourceId}>{part.code} · {part.name} · {(part.categories?.includes("ALL") || !part.categories?.length) ? (locale === "cs" ? "všechny motory" : "all engines") : part.categories.join(" / ")} · {part.quantity} {part.unit}</option>)}</select></label>}
    {item.itemType === "service" && <><label className="sale-item-resource sale-item-wide"><span>{locale === "cs" ? "Předdefinovaný servis" : "Preset service"} *</span><select required={!currentSale || !item.description || Boolean(item.resourceId)} value={item.resourceId} onChange={(event) => { const service = services.find((entry) => entry.id === event.target.value); onChange({ resourceId: event.target.value, code: service?.name ?? item.code, description: service?.descriptionCs || service?.description || service?.name || item.description, descriptionEn: service?.descriptionEn || service?.descriptionCs || service?.description || service?.name || item.descriptionEn, unitPriceCents: service ? (currency === "CZK" ? service.priceCzkCents : service.priceEurCents) : item.unitPriceCents }); }}><option value="">{currentSale && item.description && !item.resourceId ? `${locale === "cs" ? "Historický servis" : "Historical service"}: ${item.code || item.description}` : (locale === "cs" ? "Vyber servis…" : "Select service…")}</option>{services.map((service) => { const description = locale === "cs" ? (service.descriptionCs || service.description) : (service.descriptionEn || service.descriptionCs || service.description); return <option key={service.id} value={service.id}>{service.name}{description ? ` · ${description}` : ""}</option>; })}</select></label>{serviceDescription && <div className="sale-service-description"><span>{locale === "cs" ? "Popis vybraného servisu" : "Selected service description"}</span><strong>{serviceDescription}</strong></div>}</>}
    {item.itemType === "other" && <><label className="sale-item-code"><span>{locale === "cs" ? "Kód" : "Code"}</span><input value={item.code} onChange={(event) => onChange({ code: event.target.value })} /></label><label className="sale-item-description"><span>{locale === "cs" ? "Popis" : "Description"} *</span><input required value={item.description} onChange={(event) => onChange({ description: event.target.value })} /></label></>}
    <label className="sale-item-quantity"><span>{locale === "cs" ? "Množství" : "Quantity"}</span><input type="number" min="1" step="1" value={item.quantity} disabled={item.itemType === "engine" || item.itemType === "carburetor"} onChange={(event) => onChange({ quantity: Math.max(1, Number(event.target.value) || 1) })} /></label><label className="sale-item-price"><span>{locale === "cs" ? "Cena / ks" : "Unit price"} ({currency})</span><input type="number" min="0" step="0.01" value={(item.unitPriceCents / 100).toFixed(2)} disabled={item.itemType === "service"} onChange={(event) => onChange({ unitPriceCents: Math.round((Number(event.target.value) || 0) * 100) })} /></label><div className="sale-item-total"><small>{locale === "cs" ? "Mezisoučet" : "Subtotal"}</small><strong>{formatMoney(item.quantity * item.unitPriceCents, currency, locale)}</strong></div><button className="sale-item-remove" type="button" onClick={onRemove} aria-label={locale === "cs" ? "Odebrat položku" : "Remove item"}>×</button></div>;
}

function EquipmentHistoryDialog({ type, item, locale, onClose }: { type: "engine" | "carburetor"; item: SoldEquipment; locale: Locale; onClose: () => void }) {
  const [data, setData] = useState<{ assignments?: Array<Record<string, unknown>>; usage?: Array<Record<string, unknown>>; service?: Array<Record<string, unknown>>; services?: Array<Record<string, unknown>> } | null>(null); const [error, setError] = useState(false);
  useEffect(() => { const url = type === "engine" ? `/api/engine-records?engineId=${encodeURIComponent(item.id)}` : `/api/carburetor-records?id=${encodeURIComponent(item.id)}`; fetch(url, { cache: "no-store" }).then(async (response) => { if (!response.ok) throw new Error(); setData(await response.json()); }).catch(() => setError(true)); }, [item.id, type]);
  const assignments = data?.assignments ?? []; const services = data?.service ?? data?.services ?? []; const usage = data?.usage ?? [];
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="modal equipment-history-modal" role="dialog" aria-modal="true"><div className="modal-header"><div><span className="eyebrow">MM EQUIPMENT HISTORY</span><h2>{type === "engine" ? (locale === "cs" ? "Motor" : "Engine") : (locale === "cs" ? "Karburátor" : "Carburetor")} {item.code}</h2><p>{locale === "cs" ? `Prodáno ${formatDate(item.saleDate, locale)} · ${item.customerName}` : `Sold ${formatDate(item.saleDate, locale)} · ${item.customerName}`}</p></div><button className="close-button" type="button" onClick={onClose}>×</button></div>{!data && !error && <div className="empty-state"><span className="spinner" /><p>{locale === "cs" ? "Načítám kompletní historii…" : "Loading full history…"}</p></div>}{error && <p className="form-error">{locale === "cs" ? "Historii se nepodařilo načíst." : "Could not load history."}</p>}{data && <div className="equipment-history-content"><HistorySection title={locale === "cs" ? "Použití v závodech" : "Race usage"} empty={locale === "cs" ? "Bez přiřazení k závodu" : "No race assignments"}>{assignments.map((entry, index) => <div key={String(entry.id ?? index)}><strong>{String(entry.raceName ?? "—")}</strong><span>{String(entry.driverName ?? "—")}</span><small>{[entry.teamName, entry.category, entry.startDate].filter(Boolean).map(String).join(" · ")}</small></div>)}</HistorySection>{type === "engine" && <HistorySection title={locale === "cs" ? "Motohodiny" : "Running hours"} empty={locale === "cs" ? "Bez ručních záznamů" : "No manual records"}>{usage.map((entry, index) => <div key={String(entry.id ?? index)}><strong>{String(entry.entryDate ?? "—")}</strong><span>{String(entry.driverName ?? "—")}</span><small>{entry.oppamaMinutes ? `${Number(entry.oppamaMinutes) / 60} h` : String(entry.raceName ?? "")}</small></div>)}</HistorySection>}<HistorySection title={locale === "cs" ? "Servisní historie" : "Service history"} empty={locale === "cs" ? "Bez servisních záznamů" : "No service records"}>{services.map((entry, index) => <div key={String(entry.id ?? index)}><strong>{String(entry.serviceDate ?? "—")}</strong><span>{String(entry.serviceType ?? "—")}</span><small>{String(entry.mechanicName ?? entry.createdBy ?? "")}</small></div>)}</HistorySection></div>}<div className="modal-actions"><span className="modal-actions-spacer" /><button className="primary-button" type="button" onClick={onClose}>{locale === "cs" ? "Zavřít" : "Close"}</button></div></section></div>;
}
function HistorySection({ title, empty, children }: { title: string; empty: string; children: React.ReactNode[] }) { return <section className="equipment-history-section"><h3>{title}</h3>{children.length ? <div>{children}</div> : <p>{empty}</p>}</section>; }
function emptyItem(): SaleItem { return { itemType: "other", resourceId: "", category: "", code: "", description: "", descriptionEn: "", quantity: 1, unitPriceCents: 0 }; }
function categorySort(a: string, b: string) { const order = ["BABY", "MINI", "MINI U10", "MINI GR3", "OKJ", "OKN-J", "OKN", "OK", "KZ"]; return order.indexOf(a) - order.indexOf(b) || a.localeCompare(b); }
function today() { const date = new Date(); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 10); }
function formatMoney(cents: number, currency: "CZK" | "EUR", locale: Locale) { return new Intl.NumberFormat(locale === "cs" ? "cs-CZ" : "en-GB", { style: "currency", currency, minimumFractionDigits: currency === "CZK" ? 0 : 2, maximumFractionDigits: 2 }).format(cents / 100); }
export function paymentMethodLabel(method: PaymentMethod, locale: Locale) { const values: Record<PaymentMethod, [string, string]> = { cash: ["Hotově", "Cash"], card: ["Kartou", "Card"], bank_transfer: ["Převodem", "Bank transfer"], invoice: ["Faktura", "Invoice"], other: ["Jinak", "Other"] }; return values[method]?.[locale === "cs" ? 0 : 1] ?? method; }
export function saleItemDescription(item: { description: string; descriptionEn?: string }, locale: Locale) { return locale === "en" ? item.descriptionEn || item.description : item.description; }
function formatDate(value: string, locale: Locale) { const [year, month, day] = value.split("-").map(Number); return new Intl.DateTimeFormat(locale === "cs" ? "cs-CZ" : "en-GB").format(new Date(year, month - 1, day)); }
function localizeSaleError(error: string, locale: Locale) { if (locale === "en") return error; const translations: Record<string, string> = { "Valid sale date is required": "Vyplň platné datum prodeje.", "Customer is required": "Vyber nebo vyplň zákazníka.", "Select a customer or a team, not both": "Vyber buď zákazníka, nebo tým.", "Add at least one sale item": "Přidej alespoň jednu prodanou položku.", "Part description is required": "Vyplň popis ostatní položky.", "Select a specific engine or carburetor": "Vyber konkrétní motor nebo karburátor.", "Select a stock part": "Vyber konkrétní díl ze skladu.", "Select a service": "Vyber servis z ceníku.", "The same equipment cannot be sold twice": "Stejné vybavení nelze prodat dvakrát.", "Could not save sale": "Prodej se nepodařilo uložit." }; if (error.includes("has already been sold")) return error.replace("has already been sold", "už byl prodán"); if (error.includes("is assigned to")) return error.replace("is assigned to", "je přiřazen k budoucímu závodu"); if (error.startsWith("Not enough stock for ")) return error.replace("Not enough stock for ", "Nedostatečný stav skladu u ").replace("; available", "; dostupné množství"); return translations[error] ?? error; }
