import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const appUsers = sqliteTable("app_users", {
  id: text("id").primaryKey(),
  email: text("email").notNull().unique(),
  fullName: text("full_name").notNull(),
  role: text("role", { enum: ["superadmin", "boss", "mechanic"] }).notNull(),
  locale: text("locale", { enum: ["cs", "en"] }).notNull().default("cs"),
  isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const engines = sqliteTable("engines", {
  id: text("id").primaryKey(),
  code: text("code").notNull(),
  serialNumber: text("serial_number").notNull().default(""),
  brand: text("brand").notNull(),
  model: text("model").notNull(),
  category: text("category").notNull().default(""),
  family: text("family", { enum: ["MINI", "OKJ", "OKN", "OKN-J", "OK", "KZ"] }).notNull().default("OKN"),
  ignition: text("ignition", { enum: ["", "PVL", "SELETTRA"] }).notNull().default("PVL"),
  kzGeneration: text("kz_generation", { enum: ["R2", "R3"] }),
  currentConfiguration: text("current_configuration", { enum: ["MINI", "MINI 3", "MINI 4", "BABY", "BABY 3", "BABY 4"] }),
  upgradeCode: text("upgrade_code").notNull().default(""),
  labelColor: text("label_color").notNull().default(""),
  purchaseDate: text("purchase_date"),
  pistonSpec: text("piston_spec").notNull().default(""),
  cylinderCode: text("cylinder_code").notNull().default(""),
  cylinderUpgrade: text("cylinder_upgrade").notNull().default(""),
  liner: text("liner").notNull().default(""),
  degree: text("degree").notNull().default(""),
  timing: text("timing").notNull().default(""),
  carter: text("carter").notNull().default(""),
  reeds: text("reeds").notNull().default(""),
  spacer: text("spacer").notNull().default(""),
  squish: text("squish").notNull().default(""),
  status: text("status", {
    enum: ["ready", "service_soon", "service", "rebuild", "storage", "retired"],
  }).notNull().default("ready"),
  totalMinutes: integer("total_minutes").notNull().default(0),
  pistonMinutes: integer("piston_minutes").notNull().default(0),
  rodMinutes: integer("rod_minutes").notNull().default(0),
  lastOppamaMinutes: integer("last_oppama_minutes").notNull().default(0),
  currentPistonSize: text("current_piston_size").notNull().default(""),
  baselineTotalMinutes: integer("baseline_total_minutes").notNull().default(0),
  baselinePistonMinutes: integer("baseline_piston_minutes").notNull().default(0),
  baselineRodMinutes: integer("baseline_rod_minutes").notNull().default(0),
  baselineLastOppamaMinutes: integer("baseline_last_oppama_minutes").notNull().default(0),
  baselinePistonSize: text("baseline_piston_size").notNull().default(""),
  serviceIntervalMinutes: integer("service_interval_minutes").notNull().default(360),
  notes: text("notes").notNull().default(""),
  soldAt: integer("sold_at", { mode: "timestamp_ms" }),
  archivedAt: integer("archived_at", { mode: "timestamp_ms" }),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => [
  uniqueIndex("engines_code_category_unique").on(table.code, table.category),
]);

export const engineUsageLogs = sqliteTable("engine_usage_logs", {
  id: text("id").primaryKey(),
  engineId: text("engine_id").notNull(),
  entryDate: text("entry_date").notNull(),
  oppamaMinutes: integer("oppama_minutes").notNull(),
  raceName: text("race_name").notNull().default(""),
  driverName: text("driver_name").notNull().default(""),
  notes: text("notes").notNull().default(""),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
});

export const engineServiceEntries = sqliteTable("engine_service_entries", {
  id: text("id").primaryKey(),
  engineId: text("engine_id").notNull(),
  serviceDate: text("service_date").notNull(),
  serviceType: text("service_type").notNull(),
  replacedParts: text("replaced_parts").notNull().default("[]"),
  pistonSize: text("piston_size").notNull().default(""),
  notes: text("notes").notNull().default(""),
  pistonMinutesBefore: integer("piston_minutes_before").notNull().default(0),
  rodMinutesBefore: integer("rod_minutes_before").notNull().default(0),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
});

export const teams = sqliteTable("teams", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  countryCode: text("country_code").notNull().default(""),
  notes: text("notes").notNull().default(""),
  logoKey: text("logo_key"),
  logoContentType: text("logo_content_type"),
  logoUpdatedAt: integer("logo_updated_at", { mode: "timestamp_ms" }),
  archivedAt: integer("archived_at", { mode: "timestamp_ms" }),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const drivers = sqliteTable("drivers", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  teamId: text("team_id"),
  defaultCategory: text("default_category").notNull().default(""),
  raceNumber: text("race_number").notNull().default(""),
  nationality: text("nationality").notNull().default(""),
  isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
  notes: text("notes").notNull().default(""),
  archivedAt: integer("archived_at", { mode: "timestamp_ms" }),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const mechanics = sqliteTable("mechanics", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  archivedAt: integer("archived_at", { mode: "timestamp_ms" }),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const clothingItems = sqliteTable("clothing_items", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  sizes: text("sizes").notNull().default("[]"),
  defaultQuantity: integer("default_quantity").notNull().default(1),
  notes: text("notes").notNull().default(""),
  imageKey: text("image_key"),
  imageContentType: text("image_content_type"),
  imageUpdatedAt: integer("image_updated_at", { mode: "timestamp_ms" }),
  archivedAt: integer("archived_at", { mode: "timestamp_ms" }),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const mechanicClothingAssignments = sqliteTable("mechanic_clothing_assignments", {
  id: text("id").primaryKey(),
  mechanicId: text("mechanic_id").notNull(),
  clothingItemId: text("clothing_item_id").notNull(),
  size: text("size").notNull(),
  quantity: integer("quantity").notNull().default(1),
  assignedAt: integer("assigned_at", { mode: "timestamp_ms" }).notNull().default(0),
  notes: text("notes").notNull().default(""),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => [
  uniqueIndex("mechanic_clothing_unique_idx").on(table.mechanicId, table.clothingItemId),
]);

export const vehicles = sqliteTable("vehicles", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  licensePlate: text("license_plate").notNull().default(""),
  notes: text("notes").notNull().default(""),
  photoKey: text("photo_key"),
  photoContentType: text("photo_content_type"),
  photoUpdatedAt: integer("photo_updated_at", { mode: "timestamp_ms" }),
  currentKm: integer("current_km"),
  serviceIntervalKm: integer("service_interval_km"),
  lastServiceKm: integer("last_service_km"),
  lastServiceNote: text("last_service_note").notNull().default(""),
  lastServiceDate: text("last_service_date").notNull().default(""),
  archivedAt: integer("archived_at", { mode: "timestamp_ms" }),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const vehicleServiceEntries = sqliteTable("vehicle_service_entries", {
  id: text("id").primaryKey(),
  vehicleId: text("vehicle_id").notNull(),
  serviceDate: text("service_date").notNull(),
  km: integer("km"),
  workDone: text("work_done").notNull().default(""),
  mechanicId: text("mechanic_id"),
  mechanicNameSnapshot: text("mechanic_name_snapshot").notNull().default(""),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
});

export const carburetors = sqliteTable("carburetors", {
  id: text("id").primaryKey(),
  code: text("code").notNull(),
  carburetorTypeId: text("carburetor_type_id"),
  category: text("category").notNull().default(""),
  family: text("family").notNull(),
  brand: text("brand").notNull().default(""),
  model: text("model").notNull().default(""),
  status: text("status").notNull().default("ready"),
  notes: text("notes").notNull().default(""),
  soldAt: integer("sold_at", { mode: "timestamp_ms" }),
  archivedAt: integer("archived_at", { mode: "timestamp_ms" }),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const carburetorTypes = sqliteTable("carburetor_types", {
  id: text("id").primaryKey(),
  brand: text("brand").notNull(),
  model: text("model").notNull(),
  categories: text("categories").notNull().default("[]"),
  notes: text("notes").notNull().default(""),
  photoKey: text("photo_key"),
  photoContentType: text("photo_content_type"),
  photoUpdatedAt: integer("photo_updated_at", { mode: "timestamp_ms" }),
  archivedAt: integer("archived_at", { mode: "timestamp_ms" }),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const carburetorServiceEntries = sqliteTable("carburetor_service_entries", {
  id: text("id").primaryKey(),
  carburetorId: text("carburetor_id").notNull(),
  serviceDate: text("service_date").notNull(),
  serviceType: text("service_type", { enum: ["check", "routine", "full", "repair"] }).notNull(),
  mechanicId: text("mechanic_id"),
  mechanicNameSnapshot: text("mechanic_name_snapshot").notNull().default(""),
  workDone: text("work_done").notNull().default(""),
  replacedParts: text("replaced_parts").notNull().default(""),
  notes: text("notes").notNull().default(""),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
});

export const raceTemplates = sqliteTable("race_templates", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  notes: text("notes").notNull().default(""),
  seriesOptions: text("series_options").notNull().default("[]"),
  calendarColor: text("calendar_color").notNull().default("sky"),
  logoKey: text("logo_key"),
  logoContentType: text("logo_content_type"),
  logoUpdatedAt: integer("logo_updated_at", { mode: "timestamp_ms" }),
  archivedAt: integer("archived_at", { mode: "timestamp_ms" }),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const circuits = sqliteTable("circuits", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  countryCode: text("country_code").notNull(),
  address: text("address").notNull().default(""),
  websiteUrl: text("website_url").notNull().default(""),
  mapsUrl: text("maps_url").notNull().default(""),
  latitude: real("latitude"),
  longitude: real("longitude"),
  distanceKm: real("distance_km"),
  driveMinutes: integer("drive_minutes"),
  imageKey: text("image_key"),
  imageContentType: text("image_content_type"),
  imageUpdatedAt: integer("image_updated_at", { mode: "timestamp_ms" }),
  archivedAt: integer("archived_at", { mode: "timestamp_ms" }),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const races = sqliteTable("races", {
  id: text("id").primaryKey(),
  raceTemplateId: text("race_template_id"),
  circuitId: text("circuit_id"),
  name: text("name").notNull(),
  series: text("series").notNull().default(""),
  seriesRound: integer("series_round"),
  raceType: text("race_type").notNull().default(""),
  track: text("track").notNull(),
  address: text("address").notNull().default(""),
  countryCode: text("country_code").notNull(),
  startDate: text("start_date").notNull(),
  endDate: text("end_date").notNull(),
  departureDate: text("departure_date").notNull().default(""),
  returnDate: text("return_date").notNull().default(""),
  organizer: text("organizer").notNull().default(""),
  notes: text("notes").notNull().default(""),
  status: text("status", { enum: ["planned", "active", "completed", "archived"] }).notNull().default("planned"),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const raceCategories = sqliteTable("race_categories", {
  id: text("id").primaryKey(),
  raceId: text("race_id").notNull(),
  category: text("category").notNull(),
  sortOrder: integer("sort_order").notNull(),
  notes: text("notes").notNull().default(""),
});

export const raceEntries = sqliteTable("race_entries", {
  id: text("id").primaryKey(),
  raceId: text("race_id").notNull(),
  category: text("category").notNull(),
  driverId: text("driver_id").notNull(),
  driverNameSnapshot: text("driver_name_snapshot").notNull(),
  teamId: text("team_id"),
  teamNameSnapshot: text("team_name_snapshot").notNull().default(""),
  engine1Id: text("engine_1_id"),
  engine1Code: text("engine_1_code").notNull().default(""),
  engine1Configuration: text("engine_1_configuration").notNull().default(""),
  engine2Id: text("engine_2_id"),
  engine2Code: text("engine_2_code").notNull().default(""),
  engine2Configuration: text("engine_2_configuration").notNull().default(""),
  engine3Id: text("engine_3_id"),
  engine3Code: text("engine_3_code").notNull().default(""),
  engine3Configuration: text("engine_3_configuration").notNull().default(""),
  carburetor1Id: text("carburetor_1_id"),
  carburetor1Code: text("carburetor_1_code").notNull().default(""),
  carburetor2Id: text("carburetor_2_id"),
  carburetor2Code: text("carburetor_2_code").notNull().default(""),
  carburetor3Id: text("carburetor_3_id"),
  carburetor3Code: text("carburetor_3_code").notNull().default(""),
  isConfirmed: integer("is_confirmed", { mode: "boolean" }).notNull().default(false),
  notes: text("notes").notNull().default(""),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const raceEntryFinance = sqliteTable("race_entry_finance", {
  raceEntryId: text("race_entry_id").primaryKey(),
  raceId: text("race_id").notNull(),
  basePriceCents: integer("base_price_cents").notNull().default(0),
  currency: text("currency", { enum: ["CZK", "EUR"] }).notNull().default("EUR"),
  discountBasisPoints: integer("discount_basis_points").notNull().default(0),
  finalPriceCents: integer("final_price_cents").notNull().default(0),
  paymentMethod: text("payment_method", { enum: ["", "cash", "card", "bank_transfer"] }).notNull().default(""),
  isPaid: integer("is_paid", { mode: "boolean" }).notNull().default(false),
  notes: text("notes").notNull().default(""),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedBy: text("updated_by").notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const raceMechanics = sqliteTable("race_mechanics", {
  id: text("id").primaryKey(),
  raceId: text("race_id").notNull(),
  mechanicId: text("mechanic_id").notNull(),
  mechanicNameSnapshot: text("mechanic_name_snapshot").notNull(),
  vehicleId: text("vehicle_id"),
});

export const raceVehicles = sqliteTable("race_vehicles", {
  id: text("id").primaryKey(),
  raceId: text("race_id").notNull(),
  vehicleId: text("vehicle_id").notNull(),
  vehicleNameSnapshot: text("vehicle_name_snapshot").notNull(),
  licensePlateSnapshot: text("license_plate_snapshot").notNull().default(""),
});

export const raceExtras = sqliteTable("race_extras", {
  id: text("id").primaryKey(),
  raceId: text("race_id").notNull(),
  category: text("category").notNull(),
  resourceType: text("resource_type").notNull(),
  resourceId: text("resource_id").notNull(),
  resourceCodeSnapshot: text("resource_code_snapshot").notNull(),
  notes: text("notes").notNull().default(""),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
});

export const raceDeliveries = sqliteTable("race_deliveries", {
  id: text("id").primaryKey(),
  raceId: text("race_id").notNull(),
  customerName: text("customer_name").notNull(),
  description: text("description").notNull(),
  quantity: integer("quantity").notNull().default(1),
  currency: text("currency", { enum: ["CZK", "EUR"] }).notNull().default("CZK"),
  amountCents: integer("amount_cents").notNull().default(0),
  paymentMethod: text("payment_method", { enum: ["cash", "card", "bank_transfer", "invoice", "other"] }).notNull().default("cash"),
  isDelivered: integer("is_delivered", { mode: "boolean" }).notNull().default(false),
  isPaid: integer("is_paid", { mode: "boolean" }).notNull().default(false),
  notes: text("notes").notNull().default(""),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const raceFollowupNotes = sqliteTable("race_followup_notes", {
  raceId: text("race_id").primaryKey(),
  nextRace: text("next_race").notNull().default(""),
  consumed: text("consumed").notNull().default(""),
  missing: text("missing").notNull().default(""),
  otherNotes: text("other_notes").notNull().default(""),
  updatedBy: text("updated_by").notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const raceAccommodations = sqliteTable("race_accommodations", {
  id: text("id").primaryKey(),
  raceId: text("race_id").notNull(),
  name: text("name").notNull(),
  address: text("address").notNull().default(""),
  checkInDate: text("check_in_date").notNull(),
  checkOutDate: text("check_out_date").notNull(),
  reservationCode: text("reservation_code").notNull().default(""),
  websiteUrl: text("website_url").notNull().default(""),
  bookingUrl: text("booking_url").notNull().default(""),
  trackDistanceKm: real("track_distance_km"),
  trackDriveMinutes: integer("track_drive_minutes"),
  roomCount: integer("room_count").notNull().default(0),
  guestCount: integer("guest_count").notNull().default(0),
  currency: text("currency", { enum: ["CZK", "EUR"] }).notNull().default("EUR"),
  totalCents: integer("total_cents").notNull().default(0),
  paymentStatus: text("payment_status", { enum: ["unpaid", "partial", "paid"] }).notNull().default("unpaid"),
  status: text("status", { enum: ["planned", "booked", "cancelled"] }).notNull().default("planned"),
  notes: text("notes").notNull().default(""),
  archivedAt: integer("archived_at", { mode: "timestamp_ms" }),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const raceFlights = sqliteTable("race_flights", {
  id: text("id").primaryKey(),
  raceId: text("race_id").notNull(),
  direction: text("direction", { enum: ["outbound", "return", "other"] }).notNull().default("outbound"),
  tripKind: text("trip_kind", { enum: ["outbound", "return", "roundtrip", "other"] }).notNull().default("outbound"),
  departureAirport: text("departure_airport").notNull(),
  arrivalAirport: text("arrival_airport").notNull(),
  departureAt: text("departure_at").notNull(),
  arrivalAt: text("arrival_at").notNull(),
  airline: text("airline").notNull().default(""),
  flightNumber: text("flight_number").notNull().default(""),
  returnDepartureAirport: text("return_departure_airport").notNull().default(""),
  returnArrivalAirport: text("return_arrival_airport").notNull().default(""),
  returnDepartureAt: text("return_departure_at").notNull().default(""),
  returnArrivalAt: text("return_arrival_at").notNull().default(""),
  returnAirline: text("return_airline").notNull().default(""),
  returnFlightNumber: text("return_flight_number").notNull().default(""),
  reservationCode: text("reservation_code").notNull().default(""),
  returnReservationCode: text("return_reservation_code").notNull().default(""),
  passengersNote: text("passengers_note").notNull().default(""),
  passengersJson: text("passengers_json").notNull().default("[]"),
  baggage: text("baggage").notNull().default(""),
  currency: text("currency", { enum: ["CZK", "EUR"] }).notNull().default("EUR"),
  totalCents: integer("total_cents").notNull().default(0),
  status: text("status", { enum: ["planned", "booked", "cancelled"] }).notNull().default("planned"),
  notes: text("notes").notNull().default(""),
  archivedAt: integer("archived_at", { mode: "timestamp_ms" }),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const raceCarRentals = sqliteTable("race_car_rentals", {
  id: text("id").primaryKey(),
  raceId: text("race_id").notNull(),
  company: text("company").notNull(),
  vehicleType: text("vehicle_type").notNull().default(""),
  pickupPlace: text("pickup_place").notNull(),
  returnPlace: text("return_place").notNull(),
  pickupAt: text("pickup_at").notNull(),
  returnAt: text("return_at").notNull(),
  reservationCode: text("reservation_code").notNull().default(""),
  licensePlate: text("license_plate").notNull().default(""),
  driverName: text("driver_name").notNull().default(""),
  currency: text("currency", { enum: ["CZK", "EUR"] }).notNull().default("EUR"),
  totalCents: integer("total_cents").notNull().default(0),
  status: text("status", { enum: ["planned", "booked", "cancelled"] }).notNull().default("planned"),
  notes: text("notes").notNull().default(""),
  archivedAt: integer("archived_at", { mode: "timestamp_ms" }),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const travelAttachments = sqliteTable("travel_attachments", {
  id: text("id").primaryKey(),
  entityType: text("entity_type", { enum: ["accommodation", "flight", "rental"] }).notNull(),
  entityId: text("entity_id").notNull(),
  leg: text("leg", { enum: ["general", "outbound", "return"] }).notNull().default("general"),
  fileName: text("file_name").notNull(),
  objectKey: text("object_key").notNull(),
  contentType: text("content_type").notNull(),
  sizeBytes: integer("size_bytes").notNull().default(0),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => [
  index("travel_attachments_entity_idx").on(table.entityType, table.entityId, table.createdAt),
]);

export const sales = sqliteTable("sales", {
  id: text("id").primaryKey(),
  raceId: text("race_id"),
  customerId: text("customer_id"),
  teamId: text("team_id"),
  saleNumber: text("sale_number").notNull().unique(),
  saleDate: text("sale_date").notNull(),
  customerName: text("customer_name").notNull(),
  documentNumber: text("document_number").notNull().default(""),
  currency: text("currency", { enum: ["CZK", "EUR"] }).notNull().default("CZK"),
  totalCents: integer("total_cents").notNull().default(0),
  paymentMethod: text("payment_method", { enum: ["cash", "card", "bank_transfer", "invoice", "other"] }).notNull().default("cash"),
  isPaid: integer("is_paid", { mode: "boolean" }).notNull().default(false),
  isDelivered: integer("is_delivered", { mode: "boolean" }).notNull().default(false),
  notes: text("notes").notNull().default(""),
  voidedAt: integer("voided_at", { mode: "timestamp_ms" }),
  voidedBy: text("voided_by"),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const saleItems = sqliteTable("sale_items", {
  id: text("id").primaryKey(),
  saleId: text("sale_id").notNull(),
  itemType: text("item_type", { enum: ["engine", "carburetor", "part", "service", "other"] }).notNull(),
  lineKind: text("line_kind").notNull().default(""),
  resourceId: text("resource_id"),
  codeSnapshot: text("code_snapshot").notNull().default(""),
  description: text("description").notNull(),
  descriptionEnSnapshot: text("description_en_snapshot").notNull().default(""),
  quantity: integer("quantity").notNull().default(1),
  unitPriceCents: integer("unit_price_cents").notNull().default(0),
  lineTotalCents: integer("line_total_cents").notNull().default(0),
});

export const customers = sqliteTable("customers", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  phone: text("phone").notNull().default(""),
  email: text("email").notNull().default(""),
  address: text("address").notNull().default(""),
  companyId: text("company_id").notNull().default(""),
  vatId: text("vat_id").notNull().default(""),
  notes: text("notes").notNull().default(""),
  archivedAt: integer("archived_at", { mode: "timestamp_ms" }),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const serviceCatalog = sqliteTable("service_catalog", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description").notNull().default(""),
  descriptionCs: text("description_cs").notNull().default(""),
  descriptionEn: text("description_en").notNull().default(""),
  priceCzkCents: integer("price_czk_cents").notNull().default(0),
  priceEurCents: integer("price_eur_cents").notNull().default(0),
  archivedAt: integer("archived_at", { mode: "timestamp_ms" }),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const inventoryParts = sqliteTable("inventory_parts", {
  id: text("id").primaryKey(),
  code: text("code").notNull(),
  name: text("name").notNull(),
  categories: text("categories").notNull().default("[]"),
  quantity: integer("quantity").notNull().default(0),
  unit: text("unit").notNull().default("ks"),
  priceCzkCents: integer("price_czk_cents").notNull().default(0),
  priceEurCents: integer("price_eur_cents").notNull().default(0),
  notes: text("notes").notNull().default(""),
  imageKey: text("image_key"),
  imageContentType: text("image_content_type"),
  imageUpdatedAt: integer("image_updated_at", { mode: "timestamp_ms" }),
  archivedAt: integer("archived_at", { mode: "timestamp_ms" }),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const auditLogs = sqliteTable("audit_logs", {
  id: text("id").primaryKey(),
  actorEmail: text("actor_email").notNull(),
  action: text("action").notNull(),
  entityType: text("entity_type").notNull(),
  entityId: text("entity_id").notNull(),
  details: text("details").notNull().default("{}"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
});

export const workItems = sqliteTable("work_items", {
  id: text("id").primaryKey(),
  kind: text("kind", { enum: ["task", "reminder"] }).notNull().default("task"),
  title: text("title").notNull(),
  description: text("description").notNull().default(""),
  priority: text("priority", { enum: ["low", "normal", "high", "urgent"] }).notNull().default("normal"),
  status: text("status", { enum: ["open", "in_progress", "done"] }).notNull().default("open"),
  dueAt: text("due_at"),
  assigneeName: text("assignee_name").notNull().default(""),
  raceId: text("race_id"),
  completedBy: text("completed_by"),
  completedAt: integer("completed_at", { mode: "timestamp_ms" }),
  archivedAt: integer("archived_at", { mode: "timestamp_ms" }),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});
